FROM python:3.13.2-alpine3.21@sha256:323a717dc4a010fee21e3f1aac738ee10bb485de4e7593ce242b36ee48d6b352
WORKDIR /app
RUN apk update && \
    apk add --no-cache \
      py3-opencv \
      py3-pip

RUN apk --no-cache add g++ ${ADDITIONAL_PACKAGE}

# your Python deps
COPY requirements.txt .
COPY tests/requirements.tx[t] .
COPY tests/requirements-test.tx[t] .

RUN grep -vE '^(#|$|.*opencv-python.*)' requirements.txt \
  | xargs -r -n 1 python3.12 -m pip install --break-system-packages # Install all requirements except OpenCV (already covered)
RUN grep -vE '^(#|$|.*opencv-python.*)' tests/requirements.txt \
  | xargs -r -n 1 python3.12 -m pip install --break-system-packages  || \
    grep -vE '^(#|$|.*opencv-python.*)' tests/requirements-test.txt  \
  | xargs -r -n 1 python3.12 -m pip install --break-system-packages || echo "No test requirements found"

RUN pip install pytest

RUN apk info -L py3-opencv | grep cv2
RUN python3.12 -c "import sys; print(sys.path)"

# copy in code + tests
COPY . .

CMD ["sh"]