FROM python:3.13.2-alpine3.21@sha256:323a717dc4a010fee21e3f1aac738ee10bb485de4e7593ce242b36ee48d6b352
WORKDIR /app
RUN apk update && \
    apk add --no-cache \
      tcl \
      tk \
      python3-tkinter \
      xvfb \
      xdpyinfo

# your Python deps
COPY requirements.txt .
COPY tests/requirements.tx[t] tests/
COPY requirements-test.tx[t] .
COPY tests/requirements-test.tx[t] .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r tests/requirements.txt || \
    pip install --no-cache-dir -r requirements-test.txt || echo "No test requirements found"
RUN pip install pytest

# copy in code + tests
COPY . .

CMD ["sh"]